/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hijri */

#ifndef _Included_hijri
#define _Included_hijri
#ifdef __cplusplus

int intPart(int);
int* chrToIsl(int, int, int, int);
int* islToChr(int, int, int, int);
    
extern "C" {
#endif
/*
 * Class:     hijri
 * Method:    isToString
 * Signature: (IIII)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_skanderjabouzi_jnitest_MainActivity_isToString
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     hijri
 * Method:    chrToString
 * Signature: (IIII)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_skanderjabouzi_jnitest_MainActivity_chrToString
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
